context:
  name: jupyter_server_documents
  version: "0.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b8528f19006b75fe59f72fade3d28763d6432ba98d6f99412d8db1541c898e83

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - python >=3.9
    - jupyter-collaboration-ui >=2.0.2,<2.4.0
    - jupyter_server >=2.4.0,<3
    - jupyter_server_fileid >=0.9.0,<0.10.0
    - pycrdt >=0.12.49
    - jupyter_ydoc >=3.0.0,<4.0.0

tests:
  - python:
      imports:
        - jupyter_server_documents
      # Also run `pip check` to verify the integrity
      pip_check: true

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-server-documents
  repository: https://github.com/jupyter-ai-contrib/jupyter-server-documents
  summary: A JupyterLab extension that provides RTC capabilities.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrii-i
    - jtpio
    - dlqqq
    - 3coins
    - Zsailer
